# Generated by Django 5.0.3 on 2024-03-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('processor_type', models.CharField(max_length=100)),
                ('processor_speed', models.FloatField()),
                ('ram_size', models.IntegerField()),
                ('ram_type', models.CharField(max_length=50)),
                ('storage_capacity', models.IntegerField()),
                ('storage_type', models.CharField(max_length=50)),
                ('graphics_card', models.CharField(max_length=100)),
                ('screen_size', models.FloatField()),
                ('screen_resolution', models.CharField(max_length=20)),
                ('battery_life', models.FloatField()),
                ('weight', models.FloatField()),
                ('dimensions', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='laptop_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
            ],
        ),
    ]
